paulmach/orb

README.md, encoding/mvt/README.md, encoding/mvt/clip.go, encoding/mvt/clip_test.go, encoding/mvt/layer.go
I think it is useful to have the clipping functionality directly on the layers. 
This allows you to easily create vector tiles that can be rendered using mapbox-gl. 
Otherwise it is not quite obvious that you need to do the clipping and you keep wondering why there are some rendering artifacts at times. At least thats what I experienced. ^^
(addresses #3)
=> Clipping layers to bounds for MapboxGL rendering

geojson/example_pointer_test.go, geojson/example_test.go, geojson/feature.go
Have the `geojson.Feature` type implement the `orb.Pointer` interface so it can be used directly in a quadtree.  Uses the center of the bound to define the point. For something else see the example on how to define a custom type.
Discussed in https://github.com/paulmach/orb/issues/7
@s8mathur
=> geojson: have Feature implement the orb.Pointer interface

encoding/mvt/README.md, encoding/mvt/marshal.go, encoding/mvt/marshal_test.go
The encoding/mvt package converts geojson into mapbox vector tiles (mvt). The problem is [geojson](https://tools.ietf.org/html/rfc7946#section-3.2) allows ids of strings and numbers while [mvt](https://github.com/mapbox/vector-tile-spec/blob/master/1.0.1/vector_tile.proto#L30) only allows uint64 (positive numbers).  This is a common incompatibility between the two types.
For marshaling, the change is to try to convert the geojson.Feature.ID into an uint64. If it's a number type and positive, it converts to unit64. If it's a string it tries to decode.
Cavets:
* If the number is negative the feature ID will be omitted.
* If the number is a decimal, e.g. 123.45. the encode id will be the truncated, e.g. 123.
Unmarshaling code was also updated to decode ids into float64 to be consistent with …
=> marshal geojson ids into mvt uint64 if possible

encoding/wkb/scanner.go, encoding/wkb/scanner_test.go, encoding/wkb/wkb.go
see https://github.com/paulmach/orb/issues/21
when the data is nil or empty do a noop on vs. returning an error. Also the new `.Valid` attribute will be false in these cases.
=> encoding/wkb: scanner to noop on nil data

encoding/wkb/collection.go, encoding/wkb/collection_test.go, encoding/wkb/line_string.go, encoding/wkb/line_string_test.go, encoding/wkb/point.go, encoding/wkb/point_test.go, encoding/wkb/polygon.go, encoding/wkb/polygon_test.go, encoding/wkb/wkb.go
Fixes https://github.com/paulmach/orb/issues/26
Intention is to preallocate the memory needed by the item. This is great for wellformed input. However, bad data could have a big number as the first few bytes causing a large allocation to be requested. So we want to max out this preallocation to prevent that. 
In the malformed case you'd probably get a io.EOF type error.
The original code limited the allocation and the number read. Good, but very big, data was not read in completely.  Ooops....
=> encoding/wkb: Only limit allocation not reading

encoding/wkb/scanner.go, encoding/wkb/scanner_test.go
@arthurgustin
go-pg returns some(?) binary data as `\xHexvalues` vs. the binary that the library expected. PR adds some code to check for the \x prefix and does the hex -> binary conversion for the rest of the data.
I tested this with local postgis table, but only for Point data.  More testing would be helpful.
=> wkb scanner: support hex encoded data from go-pg

geojson/geometry.go, geojson/geometry_test.go
Using `UnmarshalGeometry` resulted in geometries without a `Type`. The problem was caused by the `Unmarshaller` implementation of `Geometry`.
=> fix missing Type after UnmarshalGeometry

geojson/geometry.go, geojson/geometry_test.go
Nil pointer panic occurs when `UnmarshalGeometry([]byte("null"))`
For example, javascript `JSON.parse(null)` returns `null` value.
So I think `geojson.UnmarshalGeometry([]byte("null"))` should not panic.
and... why `jg := &jsonGeometry{}; json.Unmarshal(data, &jg)` seems double pointer...?
=> Fix nil pointer err when unmarshal geojson.Geometry

geojson/README.md, geojson/bbox_test.go, geojson/example_test.go, geojson/feature.go, geojson/feature_collection.go, geojson/feature_collection_test.go, geojson/feature_test.go, geojson/properties.go, json_test.go
Foreign Members are those that aren’t in the [spec](https://tools.ietf.org/html/rfc7946#section-6.1). i.e. properties in the feature collection object that aren’t the big 3, `type`,`bbox` and `features`.
Support for this has been requested 3 times. https://github.com/paulmach/orb/issues/1 https://github.com/paulmach/orb/issues/13 https://github.com/paulmach/orb/issues/42 
This PR adds full support to those features by storing them in a `ExtraMembers` map in the feature collection.  These members will be encoded/decoded to/from the base feature collection as expected.
There was an [example](https://github.com/paulmach/orb/blob/bc42fc7d84cfdbf6ca86b63f5580a9641a2f4797/geojson/example_test.go#L29-L56) and [issue response](https://github.com/paulmach/orb/issues/1) suggesting to embed a …
=> geojson: handle extra/foreign members in featureCollection

geojson/feature.go, geojson/feature_test.go
As discussed in https://github.com/paulmach/orb/issues/38#issuecomment-760811266
nil/missing Geometry in a GeoJSON is valid according to the spec https://tools.ietf.org/html/rfc7946#section-3.2
This will change behavior as previous it would fail, now it just silently continues.
=> geojson: don't error on nil geometry

geo/distance.go, geo/distance_test.go
Added support for calculating a new point from a given point, bearing, and distance as well as a derivative function to calculate a point and bearing along a `LineString` given distance.
---
I looked for a guidelines for contributing, but didn't find any for this project. I'm open to discussion and feedback. Thanks for making this project available!
=> Add functions to calculate points based on distance and bearing

encoding/wkb/scanner.go, encoding/wkb/scanner_test.go
a wkb point is 21 bytes. mysql prefixes it with the SRID. The code to handle these 25 byte cases was not working if the SRID is 0 (default?).
Fixes https://github.com/paulmach/orb/issues/79
=> encoding/wkb: handle mysql point scanning when SRID is 0

encoding/mvt/geometry.go, encoding/mvt/marshal.go, encoding/mvt/marshal_test.go
Hi!  We've been using the library and are big fans.  I've noticed one opportunity to (potentially) improve things.  I'm trying to take an MD5 hash of the marshaled bytes to use as a fingerprint that I can compare with what the client sends me to see if they match, and it doesn't work quite right.
Currently, encode_properties iterates over a map to encode. Since there are no guarantees on iteration order for go maps, the output can differ each time for the same input. In practice, I've found the iteration order to be different almost every time.
func TestStableMarshalling(t *testing.T) {
layers := NewLayers(loadGeoJSON(t, maptile.New(17896, 24449, 16)))
values := make(map[string]bool)
for i := 0; i < 100; i++ {
marshal, _ := Marshal(layers)
checksum := md5.Sum(marshal)
sum := …
=> encoding/mvt: stable marshalling

encoding/mvt/marshal.go, encoding/mvt/marshal_test.go
support collection marshaling in mvt.
- how? :  (geometryGollection is intended to draw all the polygon in array) so just split geometryCollection to geometries
- https://docs.mapbox.com/data/tilesets/guides/vector-tiles-standards/#winding-order
- testCase 
- similar with `winding-order` sample
- <img width="852" alt="image" src="https://user-images.githubusercontent.com/28672263/156910737-0baff9ca-3ead-4658-bee0-b578bb2f9b2a.png">
=> feat(encoding/mvt): support mvt marshal for GeometryCollection

quadtree/quadtree.go, quadtree/quadtree_test.go
This PR fixes issues brought up by @hades32 in https://github.com/paulmach/orb/pull/90
Parts of the tree were getting pruned during removal, the cause is something like:
1. remove a value that was stored in a leaf node. This would make the node's value nil, but not remove the node.
2. adding some values would/could create children of this nil-value node. So you had have a nil-value node in the middle of the tree.
3. when removing a value in a parent of the original node the `removeNode` code would recurse down, find this nil-value node and remove it, along with everything under it. 
The main bug is that when adding nodes in 2, existing nil-value nodes were not reused. Also I'm unsure about the the previous removeNode code working properly.
The code assumes nil-value nodes are only in …
=> quadtree: fix cleanup of nodes during removal

encoding/wkt/README.md, encoding/wkt/unmarshal.go, encoding/wkt/unmarshal_test.go, encoding/wkt/wkt.go, encoding/wkt/wkt_test.go
just cleaning some stuff up
* encoding/wkt: expose generic Unmarshal function
* encoding/wkt: standardize errors to match other sub-packages
* encoding/wkt: fix tests
* encoding/wkt: add a Marshal method, update some comments
=> encoding/wkt: various code improvements

geo/length.go, geo/length_test.go
because it's spelled haversine....
fixes https://github.com/paulmach/orb/issues/96
=> geo: add correctly spelled LengthHaversine

README.md, geojson/README.md, geojson/feature.go, geojson/feature_collection.go, geojson/feature_collection_test.go, geojson/feature_test.go, geojson/geometry.go, geojson/json.go
**From the included readme changes**
If GeoJSON encoding/decoding performance is critical consider using a
third party replacement of "encoding/json" like [github.com/json-iterator/go](https://github.com/json-iterator/go)
This can be enabled with something like this:
```go
import (
jsoniter "github.com/json-iterator/go"
"github.com/paulmach/orb"
)
var c = jsoniter.Config{
EscapeHTML:              true,
SortMapKeys:             false,
ValidateJsonRawMessage:  false,
MarshalFloatWith6Digits: true,
}.Froze()
CustomJSONMarshaler = c
CustomJSONUnmarshaler = c
```
The above change can have dramatic performance implications, see the benchmarks below
on a 100k feature collection file:
```
benchmark                             old ns/op     new ns/op     delta
BenchmarkFeatureMarshalJSON-12 …
```
=> geojson: add support for "external" json encoders/decoders

maptile/tilecover/benchmarks_test.go, maptile/tilecover/cover_test.go, maptile/tilecover/helpers.go, maptile/tilecover/merge_test.go, maptile/tilecover/polygon.go, maptile/tilecover/polygon_test.go
When computing tile coverings there can be an error if the rings are not closed. Previously the code would panic. Now an `ErrUnevenIntersections` is returned. 
addresses https://github.com/paulmach/orb/issues/82
cc: @thisisaaronland
=> maptile/tilecover: polygon converings can return errors

README.md, encoding/mvt/README.md
Found this while copy pasting the example.
=> Fixed a small twister in README.md

quadtree/maxheap.go, quadtree/maxheap_test.go, quadtree/quadtree.go, quadtree/quadtree_test.go
Fixes https://github.com/paulmach/orb/issues/112
This was due to me being clever and trying to reuse some memory, but I was not that clever...
This does hurt the bench marks a bit, but I think it's because it's doing the right thing now
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkRandomKNearest10-10      1587          1828          +15.19%
BenchmarkRandomKNearest100-10     12826         18354         +43.10%
benchmark                         old allocs     new allocs     delta
BenchmarkRandomKNearest10-10      14             3              -78.57%
BenchmarkRandomKNearest100-10     104            3              -97.12%
benchmark                         old bytes     new bytes     delta
BenchmarkRandomKNearest10-10      472           400 …
```
=> quadtree: fix bad sort due to pointer allocation issue

geojson/example_pointer_test.go, geojson/geometry.go, geojson/geometry_test.go
turns out if you had issues with coordinates in your geojson the json error would be silently ignored.
Looks like it's been that way for a long time. https://github.com/paulmach/orb/commit/f23a70574f58f05fc956f6b2c57e1604dfde8d1c
=> geojson: ensure geometry unmarshal errors get returned

encoding/mvt/marshal_test.go
In https://github.com/paulmach/orb/pull/93 we sorted property keys to make the marshalling stable. The test for this used crypto/md5 to compare the marshallings. 
@pkumar0508 mentioned the use of crypto/md5 as a problem.
> New dependencies on crypto/md5 have been disallowed in the codebase I'm trying to use github.com/paulmach/orb in.
Just removing it and doing a direct byte comparison.
=> encoding/mvt: remove use of crypto/md5 to compare marshalling in tests

encoding/wkt/unmarshal.go, encoding/wkt/unmarshal_test.go
fixes https://github.com/paulmach/orb/issues/110
=> encoding/wkt: fix panic for some invalid wkt data

encoding/wkt/unmarshal.go, encoding/wkt/unmarshal_test.go
Even WKT specification says nothing about whitespaces around parentheses there are systems generating WKT with spaces.
This PR replaces splitting by token with splitting by regexp and adds some tests.
It should also fix https://github.com/paulmach/orb/issues/127
=> Replaced strings split with splitting by regexp

encoding/wkt/unmarshal.go, encoding/wkt/unmarshal_test.go
There is some refactoring in the validation code, but test changes are cosmetic and additions.
Fixes #130
=> encoding/wkt: better handling/validation of missing parens

maptile/tile.go, maptile/tile_test.go
Add a utility method to generate all children tiles of a tile.
=> Add ChildrenInZoomRange method

simplify/douglas_peucker.go, simplify/douglas_peucker_test.go, simplify/helpers.go, simplify/radial.go, simplify/radial_test.go, simplify/visvalingam.go, simplify/visvalingam_test.go
As described and requested in https://github.com/paulmach/orb/pull/124 by @albertyw this PR sets the "default min points" for the Visvalingam to:
* 2 if a line, already the case
* 3 for non-closed rings, rings/polygons, etc where the first point does not match the first, i.e. implicitly closed.
* 4 for closed rings
This will give polygons completely simplified a non-zero area. This should help keep the geometry valid after simplification. Note that the simplification can still cause self-intersections.
=> simplify: Visvalingam, by default, keeps 3 points for "areas"

encoding/mvt/clip.go, encoding/mvt/clip_test.go, encoding/mvt/marshal.go, encoding/mvt/marshal_test.go
Addresses an issue in https://github.com/paulmach/orb/issues/135
* will not encode features with nil geometry, used to panic
* layer.Clip() will remove the feature from the layer.Features array if it clips to nothing.
cc @polastre
=> encoding/mvt: skip encoding of features will nil geometry

geojson/feature.go, geojson/feature_collection.go, geojson/feature_collection_test.go, geojson/feature_test.go, geojson/geometry_test.go
fixes https://github.com/paulmach/orb/issues/144
If you have `{ feature: null }` and you're trying to unmarshal it into something like
```
type Struct struct {
Feature geojson.Feature `json:"feature"`
}
```
you'd get a panic. This fix sets `Struct.Feature` to an empty object. I think this is the correct behavior as you might have `{ isFeature: true, feature: null }` and you're code would check `isFeature` first.
If you really care about if it's null vs. empty you should model your data as
```
type Struct struct {
Feature *geojson.Feature `json:"feature"`
}
```
the check `Struct.Feature != nil`
=> geojson: `null` json into non-pointer Feature/FeatureCollection will set them to empty

line_string.go, line_string_test.go
Calling reverse() on an empty LineString causes a panic.
This PR handles this case and also adds it to the corresponding unit test.
The program was tested solely for our own use cases, which might differ from yours.
Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
=> Fix panic on reverse of empty linestrings

encoding/mvt/marshal.go
hi! would you be willing to support a slight refactor to marshal not just to bytes but rather to the precursor mvt spec proto objects? this is useful for grpc services which will automatically do the marshalling to bytes as part of their request handling. ive not tested this but wanted to do the PR as an illustration. let me know if its something you'd be ok supporting or not and i can write tests and clean it up if so!
=> Support for Marshalling to Proto Objects

geojson/README.md, geojson/feature.go, geojson/feature_test.go
https://github.com/paulmach/orb/pull/56 added support for ExtraMembers to feature collections, this PR adds it for features. I'm not sure if this technically allowed by the spec, but if people want to do it, now they can.
See https://github.com/paulmach/orb/pull/56 for more info about why this is necessary and how it works. 
This was requested in this issue https://github.com/paulmach/orb/issues/146
=> geojson: handle extra/foreign members in feature

internal/mercator/mercator.go, internal/mercator/mercator_test.go
This implements the fix described in #156 and adds tests to confirm it resolves the issue on `arm64` (M1 Pro Mac) and doesn't cause regressions on other architectures.
This change allows tests to now pass for me in `internal/mercator`, as well as tests in `maptile`, which were failing when testing the top-left bound of the tile for coordinates `(0, 0)`.
In passing, I noticed a transposition of variables in `TestScalarMercator` so have fixed those as well.
=> fix: return precisely 0.0 from mercator.ToGeo on arm64
